import fs from "fs";
import path from "path";

// Resolve paths relative to this script's location (backend/scripts/)
const publicDir = path.resolve(__dirname, "../public");
const outputPath = path.resolve(
  __dirname,
  "../src/generated/static-assets.ts",
);

function walk(dir: string): Record<string, string> {
  const assets: Record<string, string> = {};
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      Object.assign(assets, walk(fullPath));
    } else if (entry.isFile()) {
      const relativePath = path.relative(publicDir, fullPath);
      assets[relativePath.replace(/\\/g, "/")] =
        fs.readFileSync(fullPath).toString("base64");
    }
  }
  return assets;
}

const assets = walk(publicDir);
const count = Object.keys(assets).length;

const code = `// Auto-generated by scripts/embed-assets.ts. Do not edit.
const assetMap: Record<string, string> = ${JSON.stringify(assets, null, 2)};

export function getAsset(filePath: string): Buffer | undefined {
  const key = filePath.startsWith("/") ? filePath.slice(1) : filePath;
  const encoded = assetMap[key];
  return encoded === undefined ? undefined : Buffer.from(encoded, "base64");
}
`;

fs.writeFileSync(outputPath, code, "utf-8");
console.log(`[embed-assets] Generated ${outputPath} (${count} assets)`);
