const fs = require("fs");
const path = require("path");

const publicDir = path.resolve(__dirname, "../public");
const outputPath = path.resolve(__dirname, "../src/generated/static-assets.ts");

function walk(dir) {
  const assets = {};
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      Object.assign(assets, walk(fullPath));
    } else if (entry.isFile()) {
      const relativePath = path.relative(publicDir, fullPath);
      assets[relativePath.replace(/\\/g, "/")] =
        fs.readFileSync(fullPath).toString("base64");
    }
  }
  return assets;
}

const assets = walk(publicDir);
const count = Object.keys(assets).length;

// Also embed the seeded database if it exists
// Check both ../dev.db and ../prisma/dev.db (prisma creates it relative to schema.prisma)
const dbCandidates = [
  path.resolve(__dirname, "../dev.db"),
  path.resolve(__dirname, "../prisma/dev.db"),
];
const dbPath = dbCandidates.find(p => fs.existsSync(p));
if (dbPath) {
  assets["prisma/dev.db"] = fs.readFileSync(dbPath).toString("base64");
  console.log(`[embed-assets] Embedded database from ${path.relative(path.resolve(__dirname, ".."), dbPath)} (${(fs.statSync(dbPath).size / 1024).toFixed(1)} KB)`);
} else {
  console.warn("[embed-assets] WARNING: No dev.db found at any expected location — database will not be embedded");
}

// Also embed the SQL schema dump if it exists (for auto-initialization fallback)
const schemaCandidates = [
  path.resolve(__dirname, "../prisma/schema.sql"),
  path.resolve(__dirname, "../schema.sql"),
];
const schemaPath = schemaCandidates.find(p => fs.existsSync(p));
if (schemaPath) {
  assets["prisma/schema.sql"] = fs.readFileSync(schemaPath).toString("base64");
  console.log(`[embed-assets] Embedded SQL schema from ${path.relative(path.resolve(__dirname, ".."), schemaPath)} (${(fs.statSync(schemaPath).size / 1024).toFixed(1)} KB)`);
}

const code = `// Auto-generated by scripts/embed-assets.js. Do not edit.
const assetMap: Record<string, string> = ${JSON.stringify(assets, null, 2)};

export function getAsset(filePath: string): Buffer | undefined {
  const key = filePath.startsWith("/") ? filePath.slice(1) : filePath;
  const encoded = assetMap[key];
  return encoded === undefined ? undefined : Buffer.from(encoded, "base64");
}
`;

fs.writeFileSync(outputPath, code, "utf-8");
console.log(`[embed-assets] Generated ${outputPath} (${count} frontend assets)`);
